### ISSUE TITLE
Not work as a jar

### ISSUE THREAD

**Issue by YongtaoS** [sannies/isoviewer#15]
I have the same problem as in [Can't run as jar](https://github.com/sannies/isoviewer/issues/5) with the versions from 1.8-2.0.2. Does anyone have a solution for that? Thank you!

```
$ java -jar isoviewer-1.11-SNAPSHOT.jar 
Error: Could not find or load main class com.github.sannies.isoviewer.IsoViewerFx

$ java -jar isoviewer-2.0.2-jfx.jar 
Error: Could not find or load main class ISOViewer
```
Run in Debian 9.

**Comment by SingingTree** [comment]
This looks to happen if you're trying to run the jar with a newer version of the JRE. Looking at the manifest, we can see: `JavaFX-Version: 8.0`. Version 8 was was before JavaFX was split out of the JDK in version 11.

If I try to run 2.0.2 with JDK12 I get a similar error, but it works okay with 8.

As best I can tell, a repackage would be needed in order to get the jar to play nice with newer runtimes.

**Comment by YongtaoS** [comment]
Hi SingingTree,

Thank you very much for the reply and tips. Yes, it was due to the java version issue.
