### ISSUE TITLE
Application Not Responding on Mac

### ISSUE THREAD

**Issue by axnd** [sannies/isoviewer#3]
I just downloaded the `isoviewer-1.0.6.jar` and after inspecting one mp4 I tried to open another and the application froze with the "Application Not Responding" message in the dock. I did a Force Quit and when I try to open the `jar` file right away it starts in the "Application Not Responding" state. Interestingly enough if I Force Quit and "give it some time" (I waited ~2 minutes) ISO Viewer opens again and it reopens to the state of the previous file.

I'm on OS X 10.10.3 w/ "Java(TM) SE Runtime Environment (build 1.8.0_25-b17)"

**Comment by axnd** [comment]
This must be related to issue #1 - I deleted the video as mentioned in the comments and the app reopens instantly.

**Comment by miquelbeltran** [comment]
Same thing with version 1.0.7.

**Comment by miquelbeltran** [comment]
I've had the same problem with 1.0.7.
Mac OS X 10.10.3

The app was opening the latest mp4 I opened for some reason.
Then when loading the new mp4, it got hanged.
Deleting the old mp4 solved the issue, as the app opened "empty", and I could load the new mp4.
But opening a new mp4 again hangs the app.

Seems like the problem is that the app hangs when opening a file when there's another file loaded.

**Comment by sannies** [comment]
I removed the 'reopen last opened file' on start. So you can no longer get into this situation.
